# Copyright (C) 2017-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

name: fpga-interchange-schema-docs
channels:
- SymbiFlow
- conda-forge
- defaults
dependencies:
- python=3.7
- pip
# ReadTheDoc dependencies
- mock
- pillow
- sphinx
- sphinx_rtd_theme
# Packages installed from PyPI
- pip:
  - -r requirements.txt
